version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocritic
  disable:
    # - errcheck
    # - revive

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      -   style

formatters:
  enable:
    - gofmt
    - goimports
