services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: go-ecommerce
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:3.7
    container_name: localstack_container
    environment:
      SERVICES: s3,sqs,lambda,apigateway,dynamodb
      DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY: test
      AWS_SECRET_ACCESS_KEY: test
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"

volumes:
  postgres_data:
